modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/Sxilverrr/Spawner-Curio/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Sxilverr"
description = "A Curios necklace that speeds up nearby spawners."
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "curios"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
